installer works. Need more work for better atuomatization
git-svn-id: file:///home/koke/ebox2git/svn/branches/ubuntu-0.11.99@10018 866bc4c1-54da-0310-a958-9d5a9a0e8d04

diff --git a/extra/installer/data/ebox-installer b/extra/installer/data/ebox-installer
--- a/extra/installer/data/ebox-installer
+++ b/extra/installer/data/ebox-installer
@@ -9,10 +9,16 @@
 
 RC_NAME=ebox-installer
 
-
 mount /cdrom
-apt-cdrom add
-umount /cdrom 
+apt-cdrom add --no-mount
+APT_SUCCESS=$?
+umount /cdrom
+
+if [ $APT_SUCCESS != 0 ]; then
+    # retry prompting the user
+    apt-cdrom add
+fi
+
 
 echo Installing eBox...
 
