sync debian scripts with ubuntu-hardy-0.11.99
git-svn-id: file:///home/koke/ebox2git/svn/branches/ubuntu-0.11.99@10078 866bc4c1-54da-0310-a958-9d5a9a0e8d04

diff --git a/client/ebox/debian/ebox.postinst b/client/ebox/debian/ebox.postinst
--- a/client/ebox/debian/ebox.postinst
+++ b/client/ebox/debian/ebox.postinst
@@ -11,6 +11,20 @@ set -e
 
 #DEBHELPER#
 
+create_db() 
+{
+    db_name="eboxlogs"
+    db_user="ebox"
+
+    su postgres -c 'psql -Alt' | grep -q '^$db_name|' && db_exists=1 || db_exists=0 || true
+    if [ $db_exists -eq 0 ]; then
+        echo "Creating the $db_name database"
+        su postgres -c "createdb $db_name" > /dev/null 2>&1 || true
+        su postgres -c "createuser -R -S -D $db_user" > /dev/null 2>&1 || true
+        su postgres -c "psql -d $db_name -c \"GRANT ALL ON DATABASE $db_name TO $db_user\"" > /dev/null 2>&1 || true
+    fi
+
+}
 
 case "$1" in
 	configure)
@@ -41,6 +55,13 @@ case "$1" in
         chown -R ebox:adm /var/lib/ebox/conf
         chown -R ebox:adm /var/lib/ebox/log
  
+        # Create and set permissions for ebox.sid
+        EBOX_SID="/var/lib/ebox/conf/ebox.sid"
+        if [ ! -e $EBOX_SID ]; then
+            touch $EBOX_SID
+        fi
+        chown ebox:ebox $EBOX_SID
+        chmod 0600 $EBOX_SID
 
         # add the stderr file needed by sudo
         STDERR_FILE=`perl -MEBox::Config -e'print EBox::Config::tmp() . 'stderr'; 1'`;
@@ -55,12 +76,12 @@ case "$1" in
         chmod 0600 ${STDERR_FILE}
         chown ebox:ebox ${STDERR_FILE}
 
-		# add the dynamic www-directories
-		DYNAMIC_WWW_DIRS=$(perl -MEBox::Config -e'print EBox::Config::dynamicwww() ; print " " ; print join(" ", @{EBox::Config::dynamicwwwSubdirs()});  1;'); 
-		for DIR in $DYNAMIC_WWW_DIRS; do
-		    mkdir -p $DIR
-		    chown -R ebox.ebox $DIR
-		done
+        # add the dynamic www-directories
+        DYNAMIC_WWW_DIRS=$(perl -MEBox::Config -e'print EBox::Config::dynamicwww() ; print " " ; print join(" ", @{EBox::Config::dynamicwwwSubdirs()});  1;'); 
+        for DIR in $DYNAMIC_WWW_DIRS; do
+        mkdir -p $DIR
+        chown -R ebox.ebox $DIR
+        done
 
         #change the /var/lib/ebox/ user
         chown  ebox:ebox /var/lib/ebox
@@ -73,14 +94,26 @@ case "$1" in
         if [ ! -f /var/lib/ebox/conf/ebox.passwd ]; then
             store_password;
         fi
-        
-        set_ebox_port            
 
-        invoke-rc.d ebox apache stop || true
-        invoke-rc.d ebox apache start || true
+        #Create user and database
+        create_db
+
+        /usr/share/ebox/ebox-sql-table add admin /usr/share/ebox/sqllog/admin.sql
+
+        set_ebox_port
+
+        if [ -z "$2" ]; then
+            invoke-rc.d ebox apache start || true
+        else 
+            invoke-rc.d ebox apache stop || true
+            # Give apache some time to stop completely 
+            # Otherwise it will fail to start as the port is being used
+            sleep 5
+            invoke-rc.d ebox apache start || true
+        fi 
         
 
-		;;
+        ;;
 esac
 
 
